gpuweb/types

dist/index.d.ts

A tiny change, PTAL. @kainino0x and @austinEng .

add minBufferBindingSize into BGL

---

dist/index.d.ts

bugfix: draw call implementations should have optional arguments

---

dist/index.d.ts

reflecting changes of https://github.com/gpuweb/gpuweb/pull/1390

ref: rename depth to depthOrArrayLayers

---

dist/index.d.ts

Updating definitions to include separate GPU*BindingLayouts from spec.

Add isolated binding type definitions

---

dist/index.d.ts

Fixes two interfaces to match what's done everywhere else in the file.

change interface->class for IDL Interfaces

---

dist/index.d.ts

This does the changes to follow:
- https://github.com/gpuweb/gpuweb/pull/1322 and
- https://github.com/gpuweb/gpuweb/pull/1469

Rename vertex formats

---

dist/index.d.ts

Also fixes build I broke in #63 
TBR @austinEng

Correct type for onuncapturederror

---

README.md
dist/index.d.ts
generated/edited.d.ts

Breaks the cts build but only because it was using types in very weird ways.

Autogeneration round 4

---

.gitignore
README.md
dist/index.d.ts
generated/index.d.ts
package.json

Testing and cleaning up the roll process.

Roll gpuweb

---

dist/index.d.ts
generated/index.d.ts

- Updates timestamp mechanism
- Deprecates pipeline statistics
- Replaces depth-clamping with depth-clip-control
- Adds clearBuffer method to CommandEncoder
- Renames software adapters to fallback adapters
Had to cheat a little bit to generate, because bikeshed-to-ts isn't
working with the spec as-is.

Roll gpuweb ef3fbc5b -> 7716424b

---

dist/index.d.ts

Should have been part of #86 but slipped through, sorry!

Remove references to deprecated GPUPresentationContext

---

dist/index.d.ts
generated/index.d.ts

For cts spare color attachments update

Roll gpuweb 26e16be2b -> 3dbb79618

---

LICENSE
package.json

This follows the license in https://github.com/gpuweb/gpuweb/blob/main/LICENSE.md
FYI also @tidoust @kdashg

Add the BSD 3 Clause license.

---

dist/index.d.ts
generated/index.d.ts

Roll gpuweb 3dbb79618 -> b0f1cdf88

---

dist/index.d.ts
generated/index.d.ts

Roll gpuweb b0f1cdf -> 3745c1d

---

dist/index.d.ts
generated/index.d.ts

Roll gpuweb 3745c1d -> 4660d83

---

dist/index.d.ts

Return type for GPUInternalError constructor

---

.github/workflows/deploy-to-gh-pages.yml
.gitignore
make-webgpu-docs.mjs
package-lock.json
package.json
tsconfig.json
typedoc.json

The result is put in the `out` folder and an added github action automatically commits the out folder into the 'gh-pages' branch.

Build typedoc style docs from dist/index.d.ts

---

dist/index.d.ts
generated/index.d.ts

Update gpuweb: adds just "rgb10a2uint"

---

generated/index.d.ts

@Kangz Please review and merge

Update gpuweb: adds just unorm-10-10-10-2 vertex format

---

dist/index.d.ts
generated/index.d.ts

@Kangz Please review and publish new version.

Update gpuweb: remove unmaskhints and update GPUDepthStencilState

---

dist/index.d.ts
generated/index.d.ts

@kainino0x @toji PTAL, thanks!
This is needed for https://github.com/gpuweb/cts/pull/4003

Update gpuweb: Add float32-blendable feature

---

README.md
dist/index.d.ts
generated/index.d.ts

Translate "?" from "| null" into "null | undefined"

---

dist/index.d.ts

These are only proposals right now, but it helps give some type safety to early adopters.
Will be useful for https://github.com/webgpu/webgpu-samples/pull/494

Add maxStorage*In*Stage limits

---

dist/index.d.ts
generated/index.d.ts

https://github.com/gpuweb/gpuweb/pull/5036

Manually add the core-features-and-limits feature name

---

dist/index.d.ts
generated/index.d.ts

This is effectively just syncing with the current spec.

Pull in texture-formats-tier2

---

tests/ts5.9/package.json
tests/ts5.9/tsconfig.json

Fixes #188. Tests pass locally for me.

Test with TypeScript 5.9
