gpuweb/types

- index.d.ts
Following WebGPU spec change at https://github.com/gpuweb/gpuweb/pull/468, this PR updates updates`setVertexBuffers` to `setVertexBuffer`.
> Change setVertexBuffers to setVertexBuffer

- index.d.ts
Previously it was impossible to use e.g. GPUShaderStage[dynamicValue].
This makes that possible.
~~Documentation on "mapped object types": https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types~~ [EDIT: these aren't necessary to make this work. Just the right key type on an interface works.]
> Update types to latest gpuweb, and refactor how bitfields are expressed

- dist/index.d.ts
This prevents bugs like:
```typescript
const view: GPUTextureView = device.createTexture(desc); // no .createView()
```
Technique:
https://michalzalecki.com/nominal-typing-in-typescript/#approach-1-class-with-a-private-property
> Make WebGPU classes "nominal types" (not structural types)

- dist/index.d.ts
The member for the texture-view-dimension is of type
GPUTextureViewDimension, but the name is textureDimension, which is
confusing because there's also a type GPUTextureDimension[1][2].
[1] gpuweb/gpuweb#587
[2] gpuweb/gpuweb#589
> Replace textureDimension with viewDimension

- dist/index.d.ts
- src/constants.ts
Note this gets ahead of implementations by removing setSubData. However otherwise this should be compatible at least with current Canary (except for the many unimplemented parts).
Also takes an intermediate state in some of the ongoing spec changes (in particular mapAsync) but we'll fix that up when we have changes in the spec.
> Update to latest spec

- dist/index.d.ts
Made a mistake in #21. These should be optional.
> make depthReadOnly/stencilReadOnly optional

- dist/index.d.ts
I think that this is necessary to be able to retrieve information from a GPUQuerySet? I noticed this function was missing when trying to implement benchmarking using the timestamp-query extension. Seems to just work as expected when I added this definition to the types!
> Added resolveQuerySet to GPUCommandEncoder

- dist/index.d.ts
Without this the context return type needs to be asserted by the client which is less convenient.
> Add HTMLCanvasElement.getContext("gpupresent")

- dist/index.d.ts
This patch intends to add the member 'aspect' to GPUTextureCopyView
that follows the latest WebGPU SPEC.
> Add aspect to GPUTextureCopyView

- dist/index.d.ts
- src/constants.ts
PTAL!
Also, as a general question: Do we have backwards compatibility concerns for these files? For example, should this change leave behind a `defaultQueue` and `OUTPUT_ATTACHEMENT` declaration for some deprecation period?
> Rename OUTPUT_ATTACHMENT -> RENDER_ATTACHMENT, defaultQueue -> queue

- dist/index.d.ts
- src/constants.ts
PTAL. It looks like that we need to add the missing texture formats into gpuweb/types, in order to add them into gpuweb/cts.
> Add missing texture formats: depth16unorm, depth24unorm-stencil8, depth32float-stencil8

- dist/index.d.ts
For occlusion query, we need to pass query set through render pass descripor.
> Add occlusionQuerySet in render pass descriptor

- dist/index.d.ts
PTAL. These texture dimension limits are needed for texture size validation test in CTS when create a texture.
> Add texture dimension limits

- dist/index.d.ts
Updates `GPURenderPipelineDescriptor` and related interfaces to match the latest refactor in the spec. Marks older interfaces as deprecated.
> Updated GPURenderPipelineDescriptor definitions

- dist/index.d.ts
- generated/index.d.ts
Updating types to match the latest spec, following the instructions at https://github.com/gpuweb/types/blob/main/README.md
Includes:
- GPUCanvasCompositingAlphaMode 
- Updated GPUImageCopyImageBitmap
- GPUCompilationMessage offset/length
- Updated comments
> Roll gpuweb 1fb1ba41 -> 7d2888cd

- dist/index.d.ts
- generated/index.d.ts
Updating types to match the latest spec. Includes:
- GPUPresentationContext
- GPUExternalTexture
- importExternalTexture
- GPUImageCopyTextureTagged
- GPUPipelineConstantValue
- GPUPredefinedColorSpace 
- Updated GPUStoreOp
- nonGuaranteedFeature/Limit rename to requiredFeature/Limit
- GPUSupportedLimits
And a whole bunch of deprecated types removal.
> Roll gpuweb 7d2888cd -> eee1e8ce

- dist/index.d.ts
- remove brand from GPUCanvasContext so the intersection type works (without this the intersection is empty because there's no overlap between the `__brand` members)
- deprecate members since the intersection type mixes in with undeprecated members
> fix intersection type for getContext

- dist/index.d.ts
- generated/index.d.ts
Updating types to match the latest spec. Includes:
- 'webgpu' context type ID
- GPUInputStepMode replaced by GPUVertexStepMode
- GPUStorageTextureAccess limited to 'write-only'
- Renamed GPUPresentationContext to GPUCanvasContext
- Renamed GPUPresentationConfiguration to GPUCanvasConfiguration
- Added new GPUSupportedLimits
- requiredLimits are now specified as GPUSize64s
- Updated GPURenderBundleEncoderDescriptor
- Renamed GPUTextureUsages enums:  SAMPLED -> TEXTURE_BINDING, STORAGE -> STORAGE_BINDING
- GPUStorageTextureBindingLayout.access is nullable
And, as always, the traditional purging of deprecated types.
> Roll gpuweb eee1e8ce -> ef3fbc5b

- dist/index.d.ts
- generated/index.d.ts
The new prettier version (2.21 -> 2.4.1) seems to interpret `printWidth` differently.
Regenerate the type files for better diff view in future.
> Regenerate types to reflect prettier changes

- dist/index.d.ts
- generated/index.d.ts
- package-lock.json
- package.json
This roll also switches the bikeshed-to-ts dependency to a
personal fork (ideally temporarily) in order to resolve issues
with the use of namespaces in the spec when calling `npm generate`.
This will unblock future rolls.
The generator changes did cause some of the bitflag definitions to
be shuffled to the end of the generated document, so this PR moves
them in order to make future rolls easier.
(I will try to work with the upstream dependencies to get the
necessary bikeshed-to-ts and webidl2ts changes  landed in those
repos, because I have no desire to maintain these libraries on an
ongoing basis.)
> Roll gpuweb 7716424b -> 26e16be2b

- dist/index.d.ts
This allows code conforming to the latest spec to type-check without errors.
> Mark deprecated *LoadValue as optional

- dist/index.d.ts
- generated/index.d.ts
Small update: Add `maxColorAttachments` to `GPUSupportedLimits`
(So that we can pass test jobs for https://github.com/gpuweb/cts/pull/1520)
> Roll gpuweb a83e999 -> edca800

- dist/index.d.ts
- generated/index.d.ts
Main change:
* Add `maxDrawCount` to `GPURenderPassDescriptor`
This is needed for adding a `GPURenderPassDescriptor.maxDrawCount` test to CTS.
> Roll gpuweb edca800 -> 054fdae

- README.md
- dist/index.d.ts
Similar to GPUExtent3DStrict. Prevents the use of a `z` component in places that expect a `GPUOrigin2D`.
Fixes #104
> Add GPUOrigin2DStrict type

- dist/index.d.ts
- generated/index.d.ts
This update is needed for `rg11b10ufloat-renderable` feature test in cts.
> Roll gpuweb 054fdae -> eb06bb8

- dist/index.d.ts
- generated/index.d.ts
- package-lock.json
- package.json
Also rolls back typescript version back because of this [issue](https://stackoverflow.com/questions/73573397/when-running-npm-install-legacy-peer-deps-got-error-debug-failure-unhandled).
> Roll gpuweb eb06bb8 -> 4f639ac

- package-lock.json
- package.json
I'm assuming it wasn't intentional to make every downstream project install typescript
> move typescript to devDependencies

- dist/index.d.ts
- generated/index.d.ts
* Updated gpuweb 4f639ac -> 6d23273
* Match the latest spec
* Rename GPUShaderModule.compilationInfo to GPUShaderModule.getCompilationInfo
To reflect https://github.com/gpuweb/gpuweb/pull/3857
Needed for https://github.com/gpuweb/cts/pull/2291
> Roll gpuweb 4f639ac -> 6d23273 and rename to getCompilationInfo

- dist/index.d.ts
- generated/index.d.ts
Primarily updates the pass timestamp writes APIs, but also adds a bunch of comments to interfaces that were missing them previously.
New comments are from https://github.com/gpuweb/gpuweb/pull/4089, which hasn't landed yet. I'll update the hashes if it does prior to this CL landing.
> Roll gpuweb 1abedb51 -> 2f5c6f6c

- .github/workflows/deploy-to-gh-pages.yml
- .gitignore
- dist/index.d.ts
- package-lock.json
- package.json
- tsdoc-src/.gitignore
- tsdoc-src/generate-webgpu-ts.mjs
- tsdoc-src/package-lock.json
- tsdoc-src/package.json
- tsdoc-src/tsconfig.json
- tsdoc-src/typedoc.json
The tsdoc build broke recently because of the inclusion of VideoFrame. This fixes that, and prevents it from happening again. It also moves the build to a subdirectory cleans up the dependencies for more tests in the next PR.
I had to replace the TypeDoc API usage with a command-line invocation because I can't figure out how to enable treatWarningsAsErrors and then exit>0 in the API usage.
> Run tsdoc on PRs, move build to a subdir, fix warnings

- .github/workflows/deploy-to-gh-pages.yml
- README.md
- package.json
- tests/.gitignore
- tests/ts4.6/index.ts
- tests/ts4.6/package.json
- tests/ts4.6/tsconfig.json
- tests/ts4.7/index.ts
- tests/ts4.7/package.json
- tests/ts4.7/tsconfig.json
- tests/ts4.9/index.ts
- tests/ts4.9/package.json
- tests/ts4.9/tsconfig.json
- tests/ts5.1/index.ts
- tests/ts5.1/package.json
- tests/ts5.1/tsconfig.json
- tests/tsconfig.json
These also serve as examples of how to use these types with different TypeScript versions.
Also remove some comments from upstream that cause compilation issues in tsdoc.
Closes #127
> Add tests for build on various TypeScript versions

- dist/index.d.ts
I'm not sure which commands I missed running in https://github.com/gpuweb/types/pull/138 but this bit was missing. @Kangz Please merge and update types to 0.1.37.
Sorry for the noise.
> Adds just unorm-10-10-10-2 vertex format

- README.md
This pull request updates the installation section of the README to recommend installing @webgpu/types as a development dependency rather than a production dependency. The changes reflect the more common use case where @webgpu/types is used during development for type checking and not required in the production build.
The updated installation commands are as follows:
For npm users, the command has been changed from npm install --save @webgpu/types to npm install --save-dev @webgpu/types.
For yarn users, the command has been changed from yarn add @webgpu/types to yarn add --dev @webgpu/types.
Additionally, I've added the installation command for pnpm users: pnpm add -D @webgpu/types.
These changes ensure that the package is added to the devDependencies section of the package.json, which is …
> Update install section in README

- dist/index.d.ts
- generated/index.d.ts
@kainino0x Please review and publish new version.
> Update gpuweb: replace requestAdapterInfo() with info

- dist/index.d.ts
A constructor is needed in GPUAdapterInfo for `instanceof GPUAdapterInfo` to work (https://github.com/gpuweb/cts/pull/3679/files#diff-b1c3098d2cfb3e28e1d76d21e07c37131894fe5eeb3f55f0646c15b0f3db2b02R25).
Also, after the spec switch from IDL `interface`s to `namespace`s for bitflags, there are no longer prototypes or constructors on those objects, at least according to Chromium:
- `GPUBufferUsage instanceof Function` is false
- `'prototype' in GPUBufferUsage` is false
- `GPUBufferUsage.__proto__ === ({}).__proto__`
And they don't name types so I've removed the TS `interface`s too.
Associated CTS fixes in https://github.com/gpuweb/cts/pull/3770
> Add missing constructors, remove non-existent interfaces/prototypes/constructors

- dist/index.d.ts
This PR removes the non-standard GPUAdapter requestAdapterInfo() method which was replaced with the GPUAdapter info attribute.
> Remove non-standard GPUAdapter requestAdapterInfo() method

- dist/index.d.ts
Assuming we land https://github.com/gpuweb/gpuweb/pull/4922, `toneMapping` will be optional in practice until all browsers implement it.
> Make `getConfiguration().toneMapping` optional

- dist/index.d.ts
- generated/index.d.ts
@kainino0x Please review and publish version
> Add GPUDevice.adapterInfo

- README.md
- dist/index.d.ts
This is not standardized, but there is no harm in the types allowing it because standard implementations will simply ignore it.
> Add proposed textureBindingViewDimension

- dist/index.d.ts
this makes `addEventListener` on `GPUDevice` have the right type information.
I wasn't sure how to add it to the generated file.
> Add Event Types

- dist/index.d.ts
- generated/index.d.ts
This PR adds the subgroups feature that was added in WebGPU with https://github.com/gpuweb/gpuweb/pull/4963.
> Add subgroups feature

- dist/index.d.ts
Following https://github.com/gpuweb/gpuweb/pull/5099, this PR moves `isFallbackAdapter` into `GPUAdapterInfo`
> Move isFallbackAdapter into GPUAdapterInfo

- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy-to-gh-pages.yml
- .gitmodules
- package-lock.json
- package.json
- Add a workflow check that regenerates the file and makes sure it's up-to-date
- Pin bikeshed-to-ts as a submodule
- Update bikeshed-to-ts to a version that handles bikeshed includes (which makes the workflow check pass!)
> Pin/update bikeshed-to-ts, check generated file is up-to-date in workflow

- README.md
- dist/index.d.ts
- generated/index.d.ts
- package-lock.json
- Roll fixes in bikeshed-to-ts. None of these affect `dist/` because they were previously done manually.
- Add return types on constructors
- Add `new (): never` for objects that can't be constructed
- Translate `namespace`s into `interface`+`var` instead of just `interface`
- Nit in both bikeshed-to-ts and `dist/`
- Make the nominal typing comment smaller since there are so many copies of it
- Update README
> Roll fixes from bikeshed-to-ts

- README.md
- dist/index.d.ts
Provides some temporary safety to applications so they don't have to discover missing things when they test in other browsers.
> Mark some new additions as `?` optional

- dist/index.d.ts
- fix-generated.mjs
- generated/index.d.ts
- package.json
- tests/index.ts
- tests/ts4.6/index.ts
- tests/ts4.6/tsconfig.json
- tests/ts4.7/index.ts
- tests/ts4.7/tsconfig.json
- tests/ts4.9/index.ts
- tests/ts4.9/tsconfig.json
- tests/ts5.2/index.ts
- tests/ts5.2/tsconfig.json
- tests/ts5.8/index.ts
- tests/ts5.8/tsconfig.json
- tests/tsconfig.json
We need to use our own definition for `AllowSharedBufferSource` (here called `GPUAllowSharedBufferSource`) because the built-in one in TypeScript is broken.
Fixes #178
> "Polyfill" AllowSharedBufferSource

- dist/index.d.ts
- generated/index.d.ts
This PR reflects the following spec changes:
- https://github.com/gpuweb/gpuweb/pull/5228
> Allow GPUTexture where GPUTextureView is used
